# .github/workflows/main.yml

name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Make sure this matches your project's version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov pytest-mock # Ensure testing tools are installed

    - name: Run Pytest with Coverage
      # This 'env' block makes the secret available to the pytest command
      env:
        STRANDS_KNOWLEDGE_BASE_ID: ${{ secrets.STRANDS_KNOWLEDGE_BASE_ID }}
      run: |
        pytest tests/ -v --cov=custom_agent --cov-report=term-missing --cov-report=xml --cov-fail-under=60

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
